# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5ad850b4fb235cd180b16101a865d48171b8a6495bb024f58d1eaf8879962652f85e0c119299c8270bec2f4c01e6d3e5da1db0c4bea69ca868b73f22a19c5832

test:
  secret_key_base: f676dae11899399c37b1c9de6036ab9c3ba762ded12a8346e563de83218fc5cf4fee6cb324db3b64755e8108e3ea6a8a994d3ee1e928dbf530d8f075ace12acf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
